### ISSUE TITLE
请问作者遇到过12306查询车票 经常性 超时的情况吗，如图，thk

### ISSUE THREAD

**Issue by houxianxin** [zhibuyu/train_ticket#1]
而且查询接口，概率性 点击一次连续调用两次(没截图)，然后error

![image](https://user-images.githubusercontent.com/22886582/50470792-ffcbf800-09ec-11e9-902d-a8c7bb1da20c.png)

**Comment by zhibuyu** [comment]
暂时没有遇到，请检查下网络或代理

**Comment by houxianxin** [comment]
> 暂时没有遇到，请检查下网络或代理

好的谢谢，网络没问题，试了下正常手动也是，大概12306的锅或有什么防刷策略
