### ISSUE TITLE
票种类型选择无效

### ISSUE THREAD

**Issue by konangolden** [zhibuyu/train_ticket#2]
代码里没有将票种类型参数添加到请求参数中

**Comment by zhibuyu** [comment]
在“config.ini”这个配置文件里ticker_type里填写即可，请全部更新下

**Comment by konangolden** [comment]
再次测试，票种类型和席别选择无效，TrainTicket这两个参数获取后没有用到

**Comment by zhibuyu** [comment]
如图中设置即可，席别和自己写的不一致是因为该车次列车没有该席别的票了
![1](https://user-images.githubusercontent.com/12659236/50535929-f75cf400-0b89-11e9-85ec-dfd357c787eb.png)
![2](https://user-images.githubusercontent.com/12659236/50535927-f4620380-0b89-11e9-8f71-e36dc593a9c8.png)
