### ISSUE TITLE
老兄能不能出个具体点的指导教程

### ISSUE THREAD

**Issue by daniellauyu** [zhibuyu/train_ticket#4]
配置文件都配置好了，但是运行报了N多错，各种库也都尝试安装了。

![image](https://user-images.githubusercontent.com/17739321/50561097-6bda9300-0d42-11e9-9cee-97994e7e97bc.png)

**Comment by zhibuyu** [comment]
你的是mac还是windos,你这是你Chrome版本与chromedriver对应的版本不对，请按照我介绍里的地址去下载与你Chrome对应的chromedriver
